name: update_ncaa_playerbox

on:
  schedule:
    - cron:  '0 6 * * *'
  workflow_dispatch:

jobs:
  update-playerbox-db:
    runs-on: macOS-latest
    env: 
      ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: r-lib/actions/setup-r@v2
      - name: Update current season NCAA player box
        run: Rscript get_current_season_ncaa_playerbox.R
      - name: commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "Update NCAA Player Box" -a || echo "No changes to commit."
          git push origin main || "No changes to commit."
