name: update_ncaa_scoreboard

on:
  schedule:
    - cron:  '0 5 * * *'
  workflow_dispatch:

jobs:
  update-scoreboard-db:
    runs-on: macOS-latest
    env: 
      ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v2
      - name: Update current season NCAA scoreboard
        run: Rscript get_current_season_ncaa_scoreboard.R
