name: update_espn_scoreboard

on:
  schedule:
    - cron:  '0 5 * * *'
  workflow_dispatch:

jobs:
  update-scoreboard-db:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v2
      - name: Update current season ESPN scoreboard
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: Rscript get_current_season_espn_scoreboard.R
    
